streamer:
  image: mateuszsojka/streamer
  container_name: streamer
  ports:
   - 4200:4200
  command: ng serve --host 0.0.0.0
  environment:
    NODE_ENV: dev
  command: ng serve
  volumes:
    - .:/home/app
    - /home/app/node_modules