services:
  serve:
    image: mateuszsojka/streamer
    command: ng serve --host 0.0.0.0
    environment:
      NODE_ENV: development
    volumes:
      - .:/home/app
      - /home/app/node_modules
    ports:
      - "4200:4200"
  test:
    image: mateuszsojka/streamer
    command: ng test --browsers Chrome_no_sandbox
    environment:
      NODE_ENV: development
    volumes:
      - .:/home/app
      - /home/app/node_modules
    privileged: true
